apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-1
    app.kubernetes.io/instance: web-1
  name: web-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-1
  type: NodePort
